# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "hamano"
license = "MIT"
licenselink = "https://github.com/hamano/hugo-hamano/blob/master/LICENSE.md"
description = ""
homepage = "https://www.cuspy.org/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "HAMANO Tsukasa"
  homepage = "https://www.cuspy.org/"

